get:
  parameters:
    - $ref: '../parameters/acceptLanguage.yaml'
  summary: GET /
  description: Get metadata for the service.
  tags:
    - service metadata
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../schemas/Service.yaml'
    '400':
      $ref: '../schemas/ErrorInvalidRequest.yaml'
    '401':
      $ref: '../schemas/ErrorUnauthorized.yaml'
    '403':
      $ref: '../schemas/ErrorForbidden.yaml'
    '404':
      $ref: '../schemas/ErrorNotFound.yaml'
    '405':
      $ref: '../schemas/ErrorMethodNotImplemented.yaml'
    '429':
      $ref: '../schemas/ErrorTooManyRequests.yaml'
    '500':
      $ref: '../schemas/ErrorFatalError.yaml'
